apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-api-server
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "capi-k8s-release.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}-api
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: pre-start
          image: "{{ .Values.image.capi.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /cloud_controller_ng/pre-start.sh
          volumeMounts:
          - name: cloud-controller-ng-yaml
            mountPath: /config
      containers:
        - name: {{ .Chart.Name  }}-api-server
          image: "{{ .Values.image.capi.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # ports:
          #   - name: http
          #     containerPort: 80
          #     protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: server-sock
            mountPath: /data/cloud_controller_ng
          - name: cloud-controller-ng-yaml
            mountPath: /config
          {{- if .Values.uaa_tls_certs_secret_name }}
          - name: uaa-certs
            mountPath: /config/uaa/certs
          {{- end }}
          {{- if .Values.eirini_tls_certs_secret_name }}
          - name: eirini-certs
            mountPath: /config/eirini/certs
          {{- end }}
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 80
          volumeMounts:
          - name: nginx
            mountPath: /etc/nginx
            readOnly: true
          - name: server-sock
            mountPath: /data/cloud_controller_ng
          - name: nginx-logs
            mountPath: /cloud_controller_ng
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: server-sock
        emptyDir: {}
      - name: cloud-controller-ng-yaml
        configMap:
          name: cloud-controller-ng-yaml
      - name: nginx
        configMap:
          name: nginx
      - name: nginx-logs
        emptyDir: {}
      # TODO: use a single CA for everything plz
      {{- if .Values.uaa_tls_certs_secret_name }}
      - name: uaa-certs
        secret:
          secretName: {{ .Values.uaa_tls_certs_secret_name }}
      {{- end }}
      {{- if .Values.eirini_tls_certs_secret_name }}
      - name: eirini-certs
        secret:
          secretName: {{ .Values.eirini_tls_certs_secret_name }}
      {{- end }}

