apiVersion: v1
data:
  opi.ca: {{ .Values.apiServer.opi.ca | b64enc }}
  opi.crt: {{ .Values.apiServer.opi.client_cert | b64enc }}
  opi.key: {{ .Values.apiServer.opi.client_key | b64enc }}
kind: Secret
metadata:
  name: opi-secrets
type: Opaque
